services:
  app:
    build:
      context: .
      target: runner
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=qpon
      - DB_HOST=db
      - JWT_SECRET=secret
      - SALT_ROUNDS=10
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=qpon
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
