version: "3"

services:
  qpon-app:
    image: "891612547769.dkr.ecr.ap-south-1.amazonaws.com/org.quicko.qpon-prod:latest"
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=qpon
      - DB_HOST=qpon-db
      - JWT_SECRET=secret
      - SALT_ROUNDS=10
      - NODE_ENV=production
    depends_on:
      - qpon-db
    networks:
      - "nginxproxymanager_default"

  qpon-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=qpon
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true

volumes:
  qpon-data: