services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qpon_app
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=3000
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - JWT_SECRET=${JWT_SECRET}
      - SALT_ROUNDS=${SALT_ROUNDS}
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - qpon

  db:
    image: postgres:17
    container_name: qpon_db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"  # To connect to Postgres externally, change this to 0.0.0.0
    restart: unless-stopped
    networks:
      - qpon
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  qpon:
    driver: bridge

volumes:
  postgres_data:
